<?php
/**
 * @file
 * bysted_related_design_elements.field_group.inc
 */

/**
 * Implements hook_field_group_info().
 */
function bysted_related_design_elements_field_group_info() {
  $export = array();

  $field_group = new stdClass();
  $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
  $field_group->api_version = 1;
  $field_group->identifier = 'group_design_elements|node|bysted_page|form';
  $field_group->group_name = 'group_design_elements';
  $field_group->entity_type = 'node';
  $field_group->bundle = 'bysted_page';
  $field_group->mode = 'form';
  $field_group->parent_name = '';
  $field_group->data = array(
    'label' => 'Design elements',
    'weight' => '6',
    'children' => array(
      0 => 'field_related_design_elements',
    ),
    'format_type' => 'tab',
    'format_settings' => array(
      'formatter' => 'closed',
      'instance_settings' => array(
        'description' => '',
        'classes' => '',
        'required_fields' => 1,
      ),
    ),
  );
  $export['group_design_elements|node|bysted_page|form'] = $field_group;

  return $export;
}
